import './globals.css'
import Navbar from '@/comps/navbar'
import Footer from '@/comps/footer'

export const metadata = {
  title: 'Hero List',
  description: 'Generated by: https://bechirdev.netlify.app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="content">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
