import './globals.css'
import Navbar from '@/comps/navbar'
import Footer from '@/comps/footer'
import { Toaster, toast } from 'sonner'

export const metadata = {
  title: 'Hero List',
  description: 'Generated by: https://bechirdev.netlify.app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="content">
        <Navbar />

        {children}
        <Toaster expand={false} richColors position="top-center" />

        <Footer />
      </body>
    </html>
  )
}
